version: "3"
services:
  object-detect-app:
    stdin_open: true # for image interactive
    tty: true
    build: 
      context: ./mnt/object-detection
      dockerfile: Dockerfile
    # image: jjanzic/docker-python3-opencv
    # image: nuveo/opencv:debian-python3-opencv2
    # image: tensorflow/tensorflow:2.0.0b1-py3 
    ports: 
      - 8888:8888
      - 6006:6006
    volumes: 
      - ./mnt:/mnt
    # deploy: # CPU overload too.
    #   resources:
    #     limits:
    #       cpus: "0.30"
          # memory: "50M"
  # object-detect: ## serve API
  #   # stdin_open: true # for image interactive
  #   # tty: true # for image interactive 1 1           #   # image: jjanzic/docker-python3-opencv
  #   # image: nuveo/opencv:debian-python3-opencv2
  #   build: 
  #     context: ./
  #     dockerfile: Dockerfile
  #     args: 
  #       - model_url=http://download.tensorflow.org/models/object_detection/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz
  #   ports: 
  #     # - 8888:8888 # jupyter
  #     - 8080:8080 # tensorflow/serving API
  #     - 8081:8081 # tensorflow/serving 
  #   volumes: 
  #     # - ./mnt:/mnt
  #     -  ./mnt/tensorflow/models:/tensorflow/models
    